---
# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Add repo key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: D68FA50FEA312927     
  - name: Add repo
    apt_repository:
      repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
      state: present
      filename: mongodb
      update_cache: yes


  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: latest
      update_cache: yes 
      #    debug:
      #      msg: "В этом сценарии нужно добавить модули для установки mongodb, после можно удалить вызов модуля debug, который выводит это сообщение"


