# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Add repo key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: D68FA50FEA312927     
  - name: Add repo
    apt_repository:
      repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
      state: present
      filename: mongodb
      update_cache: yes


  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: latest
      update_cache: yes 
      #    debug:
      #      msg: "В этом сценарии нужно добавить модули для установки mongodb, после можно удалить вызов модуля debug, который выводит это сообщение"

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: all #reddit_app
  gather_facts: no
  vars:
    deploy_user: appuser

  tasks:
  - name: download files from git 
    git:
      repo: 'https://github.com/Artemmkin/reddit.git'
      dest: '/home/{{ deploy_user }}/reddit'
      version: monolith

  - name: bundle install
    bundler:
      state: present
      chdir: "/home/{{ deploy_user }}/reddit"

    handlers:
      - name: restart puma
        become: true
        systemd: name=puma state=restarted
   
- name: "Setup puma service"
  hosts: all
  gather_facts: no
  become: yes
  vars:
    deploy_user: appuser

  tasks:

  - name: add unit file for Puma
    template:
      src: puma.service.j2
      dest: /etc/systemd/system/puma.service
    notify: reload puma


  - name: enable puma
    systemd: name=puma enabled=yes

   #    debug:
    #      msg: "В этом сценарии нужно добавить модули для деплоя приложения, после можно удалить вызов модуля debug, который выводит это сообщение"

